### ISSUE TITLE
Lua runtime error

### ISSUE THREAD

**Issue by Bl4Cc4t** [ArchiveTeam/uploadir-grab#1]
Running the project via the warrior results in runtime errors:
![image](https://user-images.githubusercontent.com/6740726/208479106-7147adf1-1568-4110-ba09-d4f793f83a61.png)

https://github.com/ArchiveTeam/uploadir-grab/blob/a3187bc5210f94cfd32407e172be74f33559012b/uploadir.lua#L248
should be 
```lua
if string.match(url["url"], "^https?://uploadir%.com/uploads/[0-9a-zA-Z]+$") then
```

**Comment by Arkiver2** [comment]
Fixed with fca21df136f0136194186404fb41588ea08251b4.
